image: ghcr.io/cavoke-project/dev

tasks:
  - name: Database
    before: docker build . -f db.Dockerfile -t cavoke_db
    command: docker run -t -p 5432:5432 -e POSTGRES_USER=postgres_user -e POSTGRES_PASSWORD=postgres_password cavoke_db
  - name: Cmake
    init: cmake . -B build -DUSE_EXTERNAL_DROGON=ON -DUSE_EXTERNAL_JWT=ON -DUSE_EXTERNAL_NLOHMANN=ON -DQT_MAJOR_VERSION=5 -G Ninja

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - timonwong.shellcheck
    - ms-vscode.cmake-tools
    - vscode.cpp

#jetbrains:
#  clion:
#    prebuilds:
#      version: stable

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true