image: ghcr.io/cavoke-project/dev

tasks:
  - name: Cavoke Database
    before: docker build . -f db.Dockerfile -t cavoke_db
    command: docker run -t -p 5432:5432 cavoke_db

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - timonwong.shellcheck
    - ms-vscode.cmake-tools
    - vscode.cpp

#jetbrains:
#  clion:
#    prebuilds:
#      version: stable

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true