image:
  file: .gitpod.Dockerfile

tasks:
  - name: Database
    before: docker build . -f db.Dockerfile -t cavoke_db
    command: docker run -t -p 5432:5432 -e POSTGRES_USER=postgres_user -e POSTGRES_PASSWORD=postgres_password cavoke_db
  - name: Cmake
    init: mkdir -p build-cmake && cmake . -B build-cmake -DQT_MAJOR_VERSION=5

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - timonwong.shellcheck
#    - ms-vscode.cmake-tools
    - vscode.cpp

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true