version: 2.1

jobs:
  client-suse-qt5-notests:
    docker:
      - image: kdeorg/ci-suse-qt515
    steps:
      - run:
          name: Install KArchive
          command: zypper -n install karchive-devel
      - checkout
      - run:
          name: Cmake
          command: cmake . -DBUILD_SERVER=OFF -DQT_MAJOR_VERSION=5
      - run:
          name: Make
          command: make cavoke_client
  client-suse-qt6-notests:
    docker:
      - image: kdeorg/ci-suse-qt62
    steps:
      - checkout
      - run:
          name: Install KArchive
          command: chmod +x .circleci/suse-qt6-install-karchive.sh && .circleci/suse-qt6-install-karchive.sh
      - run:
          name: Cmake
          command: cmake . -DBUILD_SERVER=OFF -DQT_MAJOR_VERSION=6  # QT_MAJOR_VERSION=6 by default, so not necessary
      - run:
          name: Make
          command: make cavoke_client
  server-docker-healthcheck:
    docker:
      - image: drogonframework/drogon
    steps:
      - run:
          name: Install Boost
          command: apt update -y && apt install libboost-all-dev -y
      - run:
          name: Install nlohmann/json
          command: apt update -y && apt install python3-pip -y && pip3 install cget && cget install nlohmann/json
      - checkout
      - run:
          name: Cmake
          command: cmake . -DBUILD_CLIENT=OFF
      - run:
          name: Make
          command: make cavoke_server
      - run:
          name: Simple healthcheck
          command: chmod +x .circleci/server-test-health.py && .circleci/server-test-health.py ./server/cavoke_server

workflows:
  client-workflow:
    jobs:
      - client-suse-qt5-notests
      - client-suse-qt6-notests
      - server-docker-healthcheck
