version: 2.1

jobs:
  client-suse-qt5-notests:
    docker:
      - image: kdeorg/ci-suse-qt515
    steps:
      - run:
          name: Install KArchive
          command: zypper -n install karchive-devel
      - checkout
      - run:
          name: Cmake
          command: cmake . -DBUILD_ALL=OFF -DBUILD_CLIENT=ON -DQT_MAJOR_VERSION=5
      - run:
          name: Make
          command: make cavoke_client
  client-suse-qt6-notests:
    docker:
      - image: kdeorg/ci-suse-qt62
    steps:
      - checkout
      - run:
          name: Install KArchive
          command: chmod +x .circleci/suse-qt6-install-karchive.sh && .circleci/suse-qt6-install-karchive.sh
      - run:
          name: Cmake
          command: cmake . -DBUILD_ALL=OFF -DBUILD_CLIENT=ON -DQT_MAJOR_VERSION=6  # QT_MAJOR_VERSION=6 by default, so not necessary
      - run:
          name: Make
          command: make cavoke_client
  server-docker-healthcheck:
    docker:
      - image: ghcr.io/cavoke-project/cavoke_ci:drogon # TODO: use circleci orbs
        auth:
          username: $GHCR_USERNAME
          password: $GHCR_PASSWORD
    steps:
      - checkout
      - run:
          name: Cmake
          command: cmake . -DBUILD_ALL=OFF -DBUILD_SERVER=ON
      - run:
          name: Make
          command: make cavoke_server
      - run:
          name: Simple healthcheck
          command: chmod +x .circleci/server-test-health.py && .circleci/server-test-health.py ./server/cavoke_server

workflows:
  client-workflow:
    jobs:
      - client-suse-qt5-notests
      - client-suse-qt6-notests
      - server-docker-healthcheck
