/**
 *
 *  Globalstates.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Globalstates.h"
#include "Sessions.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::cavoke_test;

const std::string Globalstates::Cols::_session_id = "session_id";
const std::string Globalstates::Cols::_state = "state";
const std::string Globalstates::Cols::_is_terminal = "is_terminal";
const std::string Globalstates::primaryKeyName = "session_id";
const bool Globalstates::hasPrimaryKey = true;
const std::string Globalstates::tableName = "globalstates";

const std::vector<typename Globalstates::MetaData> Globalstates::metaData_={
{"session_id","std::string","uuid",0,0,1,1},
{"state","std::string","text",0,0,0,1},
{"is_terminal","bool","boolean",1,0,0,1}
};
const std::string &Globalstates::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Globalstates::Globalstates(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["session_id"].isNull())
        {
            sessionId_=std::make_shared<std::string>(r["session_id"].as<std::string>());
        }
        if(!r["state"].isNull())
        {
            state_=std::make_shared<std::string>(r["state"].as<std::string>());
        }
        if(!r["is_terminal"].isNull())
        {
            isTerminal_=std::make_shared<bool>(r["is_terminal"].as<bool>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 3 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            sessionId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            state_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            isTerminal_=std::make_shared<bool>(r[index].as<bool>());
        }
    }

}

Globalstates::Globalstates(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            sessionId_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            state_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            isTerminal_=std::make_shared<bool>(pJson[pMasqueradingVector[2]].asBool());
        }
    }
}

Globalstates::Globalstates(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("session_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["session_id"].isNull())
        {
            sessionId_=std::make_shared<std::string>(pJson["session_id"].asString());
        }
    }
    if(pJson.isMember("state"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["state"].isNull())
        {
            state_=std::make_shared<std::string>(pJson["state"].asString());
        }
    }
    if(pJson.isMember("is_terminal"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["is_terminal"].isNull())
        {
            isTerminal_=std::make_shared<bool>(pJson["is_terminal"].asBool());
        }
    }
}

void Globalstates::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            sessionId_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            state_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            isTerminal_=std::make_shared<bool>(pJson[pMasqueradingVector[2]].asBool());
        }
    }
}

void Globalstates::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("session_id"))
    {
        if(!pJson["session_id"].isNull())
        {
            sessionId_=std::make_shared<std::string>(pJson["session_id"].asString());
        }
    }
    if(pJson.isMember("state"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["state"].isNull())
        {
            state_=std::make_shared<std::string>(pJson["state"].asString());
        }
    }
    if(pJson.isMember("is_terminal"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["is_terminal"].isNull())
        {
            isTerminal_=std::make_shared<bool>(pJson["is_terminal"].asBool());
        }
    }
}

const std::string &Globalstates::getValueOfSessionId() const noexcept
{
    const static std::string defaultValue = std::string();
    if(sessionId_)
        return *sessionId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Globalstates::getSessionId() const noexcept
{
    return sessionId_;
}
void Globalstates::setSessionId(const std::string &pSessionId) noexcept
{
    sessionId_ = std::make_shared<std::string>(pSessionId);
    dirtyFlag_[0] = true;
}
void Globalstates::setSessionId(std::string &&pSessionId) noexcept
{
    sessionId_ = std::make_shared<std::string>(std::move(pSessionId));
    dirtyFlag_[0] = true;
}
const typename Globalstates::PrimaryKeyType & Globalstates::getPrimaryKey() const
{
    assert(sessionId_);
    return *sessionId_;
}

const std::string &Globalstates::getValueOfState() const noexcept
{
    const static std::string defaultValue = std::string();
    if(state_)
        return *state_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Globalstates::getState() const noexcept
{
    return state_;
}
void Globalstates::setState(const std::string &pState) noexcept
{
    state_ = std::make_shared<std::string>(pState);
    dirtyFlag_[1] = true;
}
void Globalstates::setState(std::string &&pState) noexcept
{
    state_ = std::make_shared<std::string>(std::move(pState));
    dirtyFlag_[1] = true;
}

const bool &Globalstates::getValueOfIsTerminal() const noexcept
{
    const static bool defaultValue = bool();
    if(isTerminal_)
        return *isTerminal_;
    return defaultValue;
}
const std::shared_ptr<bool> &Globalstates::getIsTerminal() const noexcept
{
    return isTerminal_;
}
void Globalstates::setIsTerminal(const bool &pIsTerminal) noexcept
{
    isTerminal_ = std::make_shared<bool>(pIsTerminal);
    dirtyFlag_[2] = true;
}

void Globalstates::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Globalstates::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "session_id",
        "state",
        "is_terminal"
    };
    return inCols;
}

void Globalstates::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getSessionId())
        {
            binder << getValueOfSessionId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getState())
        {
            binder << getValueOfState();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getIsTerminal())
        {
            binder << getValueOfIsTerminal();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Globalstates::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    return ret;
}

void Globalstates::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getSessionId())
        {
            binder << getValueOfSessionId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getState())
        {
            binder << getValueOfState();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getIsTerminal())
        {
            binder << getValueOfIsTerminal();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Globalstates::toJson() const
{
    Json::Value ret;
    if(getSessionId())
    {
        ret["session_id"]=getValueOfSessionId();
    }
    else
    {
        ret["session_id"]=Json::Value();
    }
    if(getState())
    {
        ret["state"]=getValueOfState();
    }
    else
    {
        ret["state"]=Json::Value();
    }
    if(getIsTerminal())
    {
        ret["is_terminal"]=getValueOfIsTerminal();
    }
    else
    {
        ret["is_terminal"]=Json::Value();
    }
    return ret;
}

Json::Value Globalstates::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 3)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getSessionId())
            {
                ret[pMasqueradingVector[0]]=getValueOfSessionId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getState())
            {
                ret[pMasqueradingVector[1]]=getValueOfState();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getIsTerminal())
            {
                ret[pMasqueradingVector[2]]=getValueOfIsTerminal();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getSessionId())
    {
        ret["session_id"]=getValueOfSessionId();
    }
    else
    {
        ret["session_id"]=Json::Value();
    }
    if(getState())
    {
        ret["state"]=getValueOfState();
    }
    else
    {
        ret["state"]=Json::Value();
    }
    if(getIsTerminal())
    {
        ret["is_terminal"]=getValueOfIsTerminal();
    }
    else
    {
        ret["is_terminal"]=Json::Value();
    }
    return ret;
}

bool Globalstates::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("session_id"))
    {
        if(!validJsonOfField(0, "session_id", pJson["session_id"], err, true))
            return false;
    }
    else
    {
        err="The session_id column cannot be null";
        return false;
    }
    if(pJson.isMember("state"))
    {
        if(!validJsonOfField(1, "state", pJson["state"], err, true))
            return false;
    }
    else
    {
        err="The state column cannot be null";
        return false;
    }
    if(pJson.isMember("is_terminal"))
    {
        if(!validJsonOfField(2, "is_terminal", pJson["is_terminal"], err, true))
            return false;
    }
    return true;
}
bool Globalstates::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Globalstates::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("session_id"))
    {
        if(!validJsonOfField(0, "session_id", pJson["session_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("state"))
    {
        if(!validJsonOfField(1, "state", pJson["state"], err, false))
            return false;
    }
    if(pJson.isMember("is_terminal"))
    {
        if(!validJsonOfField(2, "is_terminal", pJson["is_terminal"], err, false))
            return false;
    }
    return true;
}
bool Globalstates::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Globalstates::validJsonOfField(size_t index,
                                    const std::string &fieldName,
                                    const Json::Value &pJson,
                                    std::string &err,
                                    bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
            break;
    }
    return true;
}
void Globalstates::getSession(const DbClientPtr &clientPtr,
                              const std::function<void(Sessions)> &rcb,
                              const ExceptionCallback &ecb) const
{
    const static std::string sql = "select * from sessions where id = $1";
    *clientPtr << sql
               << *sessionId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Sessions(r[0]));
                    }
               }
               >> ecb;
}
