name: app
on: ['push', 'pull_request']
jobs:
  clang-format:
    name: ClangFormat 12
    runs-on: ubuntu-latest
    container: ghcr.io/cavoke-project/cavoke-ci:codeql
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
      - run: clang-format-12 --version
      - run: for file in $(find . -iname '*.cpp' -or -iname '*.c' -or -iname '*.h'); do diff -u <(cat "$file") <(clang-format-12 "$file") || exit 1; done
  cppcheck:
    name: Cppcheck
    runs-on: ubuntu-latest
    container: ghcr.io/cavoke-project/cavoke-ci:codeql
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
      - run: cppcheck --version
      - run: cppcheck --language=c++ -DSOME_DEFINE_TO_FIX_CONFIG --enable=all --suppress=*:doctest.h --suppress=unusedFunction --error-exitcode=1 --inline-suppr $(find . -iname '*.cpp')
  client-notests-qt5-suse:
    runs-on: ubuntu-latest
    container: ghcr.io/cavoke-project/cavoke-ci:client-qt5-suse
    steps:
      - uses: actions/checkout@v2
      - run: mkdir build && cd build && cmake .. -DBUILD_ALL=OFF -DBUILD_CLIENT=ON -DQT_MAJOR_VERSION=5
      - run: cd build && make cavoke_client
  client-notests-qt6-suse:
    runs-on: ubuntu-latest
    container: ghcr.io/cavoke-project/cavoke-ci:client-qt6-suse
    steps:
      - uses: actions/checkout@v2
      - run: mkdir build && cd build && cmake .. -DBUILD_ALL=OFF -DBUILD_CLIENT=ON -DQT_MAJOR_VERSION=6  # QT_MAJOR_VERSION=6 by default, so not necessary
      - run: cd build && make cavoke_client
  server-healthcheck:
    runs-on: ubuntu-latest
    container: ghcr.io/cavoke-project/cavoke-ci:server
    steps:
      - uses: actions/checkout@v2
      - run: mkdir build && cd build && cmake .. -DBUILD_ALL=OFF -DBUILD_SERVER=ON
      - run: cd build && make cavoke_server
      - run: chmod +x .github/scripts/server-test-health.py && .github/scripts/server-test-health.py ./build/server/cavoke_server
  games-notests:
    runs-on: ubuntu-latest
    container: ghcr.io/cavoke-project/cavoke-ci:server
    steps:
      - uses: actions/checkout@v2
      - run: mkdir build && cd build && cmake .. -DBUILD_ALL=OFF -DBUILD_GAMES=ON
      - run: cd build && make all
