name: Deploy and Bundle Client
on: workflow_call
jobs:
  bundle-client-unix:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cache Qt
        id: cache-qt-unix
        uses: actions/cache@v1
        with:
          path: ./Qt
          key: ${{ runner.os }}-QtCache-${{ env.QT_CACHE_ITERATION }}
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache-qt-unix.outputs.cache-hit }}
          tools: 'tools_ifw,4.3.0-0-202202240617,qt.tools.ifw.43'  # todo don't specify raw version...
          modules: 'qtnetworkauth'
      - name: Install KArchive (Unix)
        run: |
          mkdir build-zlib
          cmake -B build-zlib ./third_party/zlib
          sudo cmake --build build-zlib --target install
          mkdir build-ECM
          cmake -B build-ECM ./third_party/extra-cmake-modules
          sudo cmake --build build-ECM --target install
          mkdir build-karchive
          cmake -B build-karchive ./third_party/karchive
          sudo cmake --build build-karchive --target install
      - name: Cmake
        run: |
          mkdir -p build && cmake . -B build -DBUILD_ALL=OFF -DBUILD_CLIENT=ON -DQT_MAJOR_VERSION=5 -DCPACK_IFW_ROOT="${IQTA_TOOLS}/QtInstallerFramework/4.3" --config Release
          cmake . -B build --target bundle --config Release
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
      fail-fast: false
  bundle-client-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cache Qt
        id: cache-qt-windows
        uses: actions/cache@v1
        with:
          path: ./Qt
          key: ${{ runner.os }}-QtCache-${{ env.QT_CACHE_ITERATION }}
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache-qt-windows.outputs.cache-hit }}
          tools: 'tools_ifw,4.3.0-0-202202240617,qt.tools.ifw.43'  # todo don't specify raw version...
          modules: 'qtnetworkauth'
      - name: Install KArchive (Windows)
        run: |
          mkdir build-zlib
          cmake -B build-zlib ./third_party/zlib
          cmake --build build-zlib --target install
          mkdir build-ECM
          cmake -B build-ECM ./third_party/extra-cmake-modules
          cmake --build build-ECM --target install
          mkdir build-karchive
          cmake -B build-karchive ./third_party/karchive
          cmake --build build-karchive --target install
          mkdir build && cmake . -B build -DBUILD_ALL=OFF -DBUILD_CLIENT=ON -DQT_MAJOR_VERSION=5 -DKF5Archive_DIR="C:/Program Files (x86)/ECM/lib/cmake/KF5Archive" -DCPACK_IFW_ROOT="${IQTA_TOOLS}/QtInstallerFramework/4.3" --config Release
          cmake . -B build --target bundle --config Release
env:
  QT_CACHE_ITERATION: 1
