name: doxygen

on: push

#on:
#  push:
#    branches:
#      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Doxygen 1.9.2 + CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz libclang-cpp1-9 libclang1-9 cmake
          wget https://www.doxygen.nl/files/doxygen-1.9.2.linux.bin.tar.gz
          tar -xvzf doxygen-1.9.2.linux.bin.tar.gz
          ln -s doxygen-1.9.2/bin/doxygen doxygen && sudo cp doxygen /usr/local/bin
      - name: Generate Documentation
        run: cmake -B build . -DBUILD_ALL=OFF && cmake --build build --target docs
      - name: Git add & commit
        run: |
          cd docs/html
          git init
          git add -A
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Publishing Doxygen"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: docs/html
