name: Run Tests
on:
  workflow_call
jobs:
  clang-format:
    name: ClangFormat 12
    runs-on: ubuntu-latest
    container: ghcr.io/cavoke-project/cavoke-ci:codeql
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
        # do not check submodules
      - run: clang-format-12 --version
      - run: chmod +x .github/scripts/diff-clangformat-12.sh && find . \( -iname '*.cpp' -or -iname '*.c' -or -iname '*.h' \) -and -not -path './server/models/*' | xargs -n1 .github/scripts/diff-clangformat-12.sh
  cppcheck:
    name: Cppcheck
    runs-on: ubuntu-latest
    container: ghcr.io/cavoke-project/cavoke-ci:codeql
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
        # do not check submodules
      - run: cppcheck --version
      - run: cppcheck --language=c++ -DSOME_DEFINE_TO_FIX_CONFIG --enable=all --suppress=*:doctest.h --suppress=unusedFunction --error-exitcode=1 --inline-suppr $(find . -iname '*.cpp' -and -not -path './server/models/*')
  client-notests-qt5-suse:
    runs-on: ubuntu-latest
    container: ghcr.io/cavoke-project/cavoke-ci:client-qt5-suse
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cmake
        run: mkdir build && cd build && cmake .. -DBUILD_ALL=OFF -DBUILD_CLIENT=ON -DQT_MAJOR_VERSION=5
      - name: Make
        run: cd build && make cavoke_client
  client-notests-qt6-suse:
    runs-on: ubuntu-latest
    container: ghcr.io/cavoke-project/cavoke-ci:client-qt6-suse
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cmake
        run: mkdir build && cd build && cmake .. -DBUILD_ALL=OFF -DBUILD_CLIENT=ON -DQT_MAJOR_VERSION=6  # QT_MAJOR_VERSION=6 by default, so not necessary
      - name: Make
        run: cd build && make cavoke_client
  server-compiles-with-submodules:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update && sudo apt-get install -y openssl libssl-dev libjsoncpp-dev uuid-dev zlib1g-dev libc-ares-dev postgresql-server-dev-all libboost-all-dev
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cache Cmake
        id: cache-cmake
        uses: actions/cache@v3
        with:
          path: build
          key: cache-cmake-with-submodules
      - name: Cmake
        run: mkdir -p build && cd build && cmake .. -DBUILD_ALL=OFF -DBUILD_SERVER=ON
      - name: Make
        run: cd build && make cavoke_server
  server-healthcheck:
    runs-on: ubuntu-latest
    container: ghcr.io/cavoke-project/cavoke-ci:server
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: cavoke
          POSTGRES_PASSWORD: postgres_password
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres_user
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./server/pytest/test-requirements.txt
      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client
      - name: Populate the database
        run: psql -h postgres -d cavoke -U postgres_user -f server/db/schema.sql
        env:
          PGPASSWORD: postgres_password
      - name: Cmake
        run: mkdir build && cd build && cmake .. -DBUILD_ALL=OFF -DBUILD_SERVER=ON -DUSE_EXTERNAL_DROGON=ON -DUSE_EXTERNAL_NLOHMANN=ON -DUSE_EXTERNAL_JWT=ON
      - name: Make
        run: cd build && make cavoke_server
      - name: Pytest (Healthcheck)
        run: |
          pytest ./server/pytest --servercmd "./build/server/cavoke_server -c .github/files/ci_server_config.json -p 8080" --endpoint "http://localhost:8080" -k 'test_health'
  server-tests:
    runs-on: ubuntu-latest
    container: ghcr.io/cavoke-project/cavoke-ci:server
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cmake
        run: mkdir build && cd build && cmake .. -DBUILD_ALL=OFF -DBUILD_SERVER=ON -DUSE_EXTERNAL_DROGON=ON -DUSE_EXTERNAL_NLOHMANN=ON -DUSE_EXTERNAL_JWT=ON
      - name: Make
        run: cd build && make cavoke_server_test
      - name: Run Tests
        run: ./build/server/test/cavoke_server_test
  games-notests:
    runs-on: ubuntu-latest
    container: ghcr.io/cavoke-project/cavoke-ci:server
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cmake
        run: mkdir build && cd build && cmake .. -DBUILD_ALL=OFF -DBUILD_GAMES=ON -DUSE_EXTERNAL_DROGON=ON -DUSE_EXTERNAL_NLOHMANN=ON -DUSE_EXTERNAL_JWT=ON
      - name: Make
        run: cd build && make all
  server-docker-compose-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        threads_num: [1, 4]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install sponge
        run: apt install -y moreutils
      - name: Set the number of threads (${{ matrix.threads_num }})
        run: jq '.app.number_of_threads = ${{ matrix.threads_num }}' example/server_data/drogon_config.json | sponge example/server_data/drogon_config.json 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./server/pytest/test-requirements.txt
      - name: Start up the server with Docker Compose
        run: docker-compose up -d
      - name: Healthcheck
        run: test $(curl -s localhost:8080/health) = "OK"
      - name: Check that some games are available
        run: curl -s localhost:8080/games/list | jq -e 'length >= 1'
      - name: Pytest
        run: |
          pytest ./server/pytest --endpoint "http://localhost:8080"
